Added cache warm-up side container in juno charts

diff --git a/charts/juno-node/templates/statefulset.yaml b/charts/juno-node/templates/statefulset.yaml
--- a/charts/juno-node/templates/statefulset.yaml
+++ b/charts/juno-node/templates/statefulset.yaml
@@ -99,7 +99,50 @@ spec:
           limits:
             memory: {{ .Values.pgo.resources.limits.memory }}
             cpu: {{ .Values.pgo.resources.limits.cpu }}
-      {{- end }}      
+      {{- end }} 
+      {{- if .Values.cache.enabled }}
+      - name: {{ .Values.deployment.projectName }}-cache
+        image: {{ .Values.cache.image }}
+        imagePullPolicy: Always       
+        command:
+        - /bin/sh
+        - -c  
+        - |
+          echo "Starting curl requests";
+          counter=0
+          max_retries=60
+          while [ $counter -lt $max_retries ]; do
+            echo "Attempt $((counter + 1)): curl req started"
+
+            response=$(curl --location 'localhost:6060' \
+                --header 'Content-Type: application/json' \
+                --data '{"jsonrpc":"2.0","method":"starknet_call","params":{"block_id":{"block_number":642736},"request":{"calldata":["0x3E","0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x0","0x1","0x3fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1","0x1","0xda114221cb83fa859dbdb4c44beeaa0bb37c7537ad5ae66fe5e0efd20e6eb3","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2","0x1","0x68f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x3","0x1","0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x4","0x1","0x29959a546dda754dc823a7b8aa65862c5825faeaaf7938741d8ca6bfdc69e4e","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x5","0x1","0x70f8a4fcd75190661ca09a7300b7c93fab93971b67ea712c664d7948a8a54c6","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x6","0x1","0x40b091cb020d91f4a4b34396946b4d4e2a450dbd9410432ebdbfe10e55ee5e5","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x7","0x1","0x6a05844a03bb9e744479e3298f54705a35966ab04140d3d8dd797c1f6dc49d0","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x8","0x1","0x42b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x9","0x1","0x14e644c20bd5f9888033d2093c8ba3334caa0c7d15ed142962a9bebf36cc7e0","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xa","0x1","0x124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xb","0x1","0x70a76fd48ca0ef910631754d77dd822147fe98a569b826ec85e3c33fde586ac","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xc","0x1","0x1e0eee22c684fdf32babdd65e6bcca62a8ce2c23c8d5e68f3989595d26e1b4a","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xd","0x1","0x22b05f9396d2c48183f6deaf138a57522bcc8b35b67dee919f76403d1783136","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xe","0x1","0x7c662b10f409d7a0a69c8da79b397fd91187ca5f6230ed30effef2dceddc5b3","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0xf","0x1","0x25b392609604c75d62dde3d6ae98e124a31b49123b8366d7ce0066ccb94f696","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x10","0x1","0x41f9a1e9a4d924273f5a5c0c138d52d66d2e6a8bee17412c6b0f48fe059ae04","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x11","0x1","0x1ea237607b7d9d2e9997aa373795929807552503683e35d8739f4dc46652de1","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x12","0x1","0x611e8f4f3badf1737b9e8f0ca77dd2f6b46a1d33ce4eed951c6b18ac497d505","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x13","0x1","0x2699b69786cb08b4c83c1c02e943eca3eba00234d80a564ebe00c40226ea70b","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x14","0x1","0x4d0390b777b424e43839cd1e744799f3de6c176c7e32c1812a41dbd9c19db6a","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x15","0x1","0x45e7131d776dddc137e30bdd490b431c7144677e97bf9369f629ed8d3fb7dd6","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x16","0x1","0x5801bdad32f343035fb242e98d1e9371ae85bc1543962fedea16c59b35bd19b","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x17","0x1","0x7e2a13b40fc1119ec55e0bcf9428eedaa581ab3c924561ad4e955f95da63138","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x18","0x1","0xcfd39f5244f7b617418c018204a8a9f9a7f72e71f0ef38f968eeb2a9ca302b","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x19","0x1","0x260e98362e0949fefff8b4de85367c035e44f734c9f8069b6ce2075ae86b45c","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1a","0x1","0xf0f5b3eed258344152e1f17baf84a2e1b621cd754b625bec169e8595aea767","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1b","0x1","0x5a8054e5ca0b277b295a830e53bd71a6a6943b42d0dbb22329437522bc80c8","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1c","0x1","0x39c183c8e5a2df130eefa6fbaa3b8aad89b29891f6272cb0c90deaa93ec6315","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1d","0x1","0x44d13ad98a46fd2322ef2637e5e4c292ce8822f47b7cb9a1d581176a801c1a0","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1e","0x1","0x32ebb8e68553620b97b308684babf606d9556d5c0a652450c32e85f40d000d","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x1f","0x1","0x30615bec9c1506bfac97d9dbd3c546307987d467a7f95d5533c2e861eb81f3f","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x20","0x1","0x15e9cd2d4d6b4bb9f1124688b1e6bc19b4ff877a01011d28c25c9ee918e83e5","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x21","0x1","0x2aab581754064a87ade1b680fd9756dc3a17440a87aaf496dcfb39fd163d1dd","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x22","0x1","0x601f72228f73704e827de5bcd8dadaad52c652bb1e42bf492d90bbe22df2cec","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x23","0x1","0x6e1ed57b7e9fed35364ca419340c47479e93206a2dcda5e50530ae198d872ea","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x24","0x1","0x691fa7f66d63dc8c89ff4e77732fff5133f282e7dbd41813273692cc595516","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x25","0x1","0x5e86d570376e8dc917d241288150a3286c8ad7151638c152d787eca2b96aec3","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x26","0x1","0xa144ef99419e4dbb3ef99bc2db894fbe7b4532ebed9592a407908727321fcf","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x27","0x1","0x44d9bb78a92132eb8d7a73eac2937fa71e609b33538c87cf7448f22760ce4b6","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x28","0x1","0x41a708cf109737a50baa6cbeb9adf0bf8d97112dc6cc80c7a458cbad35328b0","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x29","0x1","0xf9d8f827734f5fd54571f0e78398033a3c1f1074a471cd4623f2aa45163718","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2a","0x1","0x22e45d94d5c6c477d9efd440aad71b2c02a5cd5bed9a4d6da10bb7c19fd93ba","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2b","0x1","0x2e767b996c8d4594c73317bb102c2018b9036aee8eed08ace5f45b3568b94e5","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2c","0x1","0x17e9e62c04b50800d7c59454754fe31a2193c9c3c6c92c093f2ab0faadf8c87","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2d","0x1","0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2e","0x1","0x319111a5037cbec2b3e638cc34a3474e2d2608299f3e62866e9cc683208c610","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x2f","0x1","0x1fa2fb85f624600112040e1f3a848f53a37ed5a7385810063d5fe6887280333","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x30","0x1","0x9c6b4fb13dfaa025c1383ed6190af8ed8cbb09d9588a3bb020feb152442406","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x31","0x1","0x58efd0e73c33a848ffaa88738d128ebf0af98ea78cf3c14dc757bb02d39ffb","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x32","0x1","0x4578fffc279e61b5cb0267a5f8e24b6089d40f93158fbbad2cb23b8622c9233","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x33","0x1","0x49210ffc442172463f3177147c1aeaa36c51d152c1b0630f2364c300d4f48ee","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x34","0x1","0x39877a272619050ab8b0e3e0a19b58d076fc2ce84da1dc73b699590e629f2b8","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x35","0x1","0x137dfca7d96cdd526d13a63176454f35c691f55837497448fad352643cfe4d4","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x36","0x1","0x3a6ec0b0ea7a1903329d5dec4bb574ecb4d6fdc206664e1c61eeded8158ab40","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x37","0x1","0x6cead2351c6fc93ccf3a43d4ddb645d0c851c1827b0332e3ac0c5c89d6560db","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x38","0x1","0x26e0852e1de834db3858b644270c52c4e0cab5be1da710751711c11b74eefed","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x39","0x1","0x30c42f4c0a094ea1eda7e3086056a225a464c43dd7da48bd2083fc3114a4db","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x3a","0x1","0x782f0ddca11d9950bc3220e35ac82cf868778edb67a5e58b39838544bc4cd0f","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x3b","0x1","0x5574eb6b8789a91466f902c380d978e472db68170ff82a5b650b95a58ddf4ad","0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x3c","0x1","0x049D36570D4e46f48e99674bd3fcc84644DdD6b96F7C741B1562B82f9e004dC7","0x02e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e","0x3d","0x1","0x3E","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x1884b27a9b015dd917ab9837c65ff0ed69b37f449f837f0c3740dcb4b6b27f7","0x06e18dd81378fd5240704204bccc546f6dfad3d08c4a3a44347bd274659ff328"],"contract_address":"0x163dd8182a69972b9fc7e95eb0be92b731680212beddfede2eff4ffcfa28bfb","entry_point_selector":"0x24c7ee658acc0eb4da5d128b6f216a0156f1bcd4e92f63e949b495a3be3772f"}},"id":1}')
+
+            echo "$response"
+            if echo "$response" | jq -e '.result' > /dev/null 2>&1; then
+              echo "req completed"
+              break; 
+            else
+              echo "Request succeeded but no result field, retrying in 500ms..."           
+            fi
+            echo "Request failed, retrying in 500ms..."
+            sleep 0.5
+            counter=$((counter + 1))
+          done
+          if [ $counter -ge $max_retries ]; then
+            echo "Max retries reached, exiting."
+            exit 1
+          fi
+          sleep infinity
+              
+        resources:
+          requests:
+            memory: {{ .Values.cache.resources.requests.memory }}
+            cpu: {{ .Values.cache.resources.requests.cpu }}
+          limits:
+            memory: {{ .Values.cache.resources.limits.memory }}
+            cpu: {{ .Values.cache.resources.limits.cpu }}                  
+      {{- end }} 
       - name: {{ .Values.deployment.projectName }}
         image: {{ .Values.deployment.imagename }}:{{ .Values.deployment.imagetag }}
         imagePullPolicy: Always
